export const seededQuestions = [
  {
    id: 1,
    title: "Two Sum",
    difficulty: "Easy",
    topics: ["Arrays", "HashMap"],
    lists: ["Blind75", "Neetcode150", "StriverA2Z"],
    link: "https://leetcode.com/problems/two-sum/",
    platform: "LeetCode",
  },
  {
    id: 2,
    title: "Valid Anagram",
    difficulty: "Easy",
    topics: ["Arrays", "Strings", "HashMap"],
    lists: ["Blind75", "Neetcode150", "StriverA2Z"],
    link: "https://leetcode.com/problems/valid-anagram/",
    platform: "LeetCode",
  },
  {
    id: 3,
    title: "Contains Duplicate",
    difficulty: "Easy",
    topics: ["Arrays", "HashMap", "HashSet"],
    lists: ["Blind75", "Neetcode150", "StriverA2Z"],
    link: "https://leetcode.com/problems/contains-duplicate/",
    platform: "LeetCode",
  },
  {
    id: 4,
    title: "Group Anagrams",
    difficulty: "Medium",
    topics: ["Arrays", "Strings", "HashMap"],
    lists: ["Blind75", "Neetcode150", "StriverA2Z"],
    link: "https://leetcode.com/problems/group-anagrams/",
    platform: "LeetCode",
  },
  {
    id: 5,
    title: "Top K Frequent Elements",
    difficulty: "Medium",
    topics: ["Arrays", "HashMap", "Heap"],
    lists: ["Blind75", "Neetcode150", "StriverA2Z"],
    link: "https://leetcode.com/problems/top-k-frequent-elements/",
    platform: "LeetCode",
  },
  {
    id: 6,
    title: "Product of Array Except Self",
    difficulty: "Medium",
    topics: ["Arrays", "Prefix Sum"],
    lists: ["Blind75", "Neetcode150", "StriverA2Z"],
    link: "https://leetcode.com/problems/product-of-array-except-self/",
    platform: "LeetCode",
  },
  {
    id: 7,
    title: "Longest Consecutive Sequence",
    difficulty: "Medium",
    topics: ["Arrays", "HashSet"],
    lists: ["Blind75", "Neetcode150", "StriverA2Z"],
    link: "https://leetcode.com/problems/longest-consecutive-sequence/",
    platform: "LeetCode",
  },

  {
    id: 8,
    title: "Valid Palindrome",
    difficulty: "Easy",
    topics: ["Strings", "Two Pointers"],
    lists: ["Blind75", "Neetcode150"],
    link: "https://leetcode.com/problems/valid-palindrome/",
    platform: "LeetCode",
  },
  {
    id: 9,
    title: "3Sum",
    difficulty: "Medium",
    topics: ["Arrays", "Two Pointers"],
    lists: ["Blind75", "Neetcode150", "StriverA2Z"],
    link: "https://leetcode.com/problems/3sum/",
    platform: "LeetCode",
  },
  {
    id: 10,
    title: "Container With Most Water",
    difficulty: "Medium",
    topics: ["Arrays", "Two Pointers", "Greedy"],
    lists: ["Blind75", "Neetcode150", "StriverA2Z"],
    link: "https://leetcode.com/problems/container-with-most-water/",
    platform: "LeetCode",
  },
  {
    id: 11,
    title: "Trapping Rain Water",
    difficulty: "Hard",
    topics: ["Arrays", "Two Pointers", "DP"],
    lists: ["Blind75", "Neetcode150", "StriverA2Z"],
    link: "https://leetcode.com/problems/trapping-rain-water/",
    platform: "LeetCode",
  },
  {
    id: 12,
    title: "Best Time to Buy and Sell Stock",
    difficulty: "Easy",
    topics: ["Arrays", "Sliding Window", "DP"],
    lists: ["Blind75", "Neetcode150", "StriverA2Z"],
    link: "https://leetcode.com/problems/best-time-to-buy-and-sell-stock/",
    platform: "LeetCode",
  },
  {
    id: 13,
    title: "Longest Substring Without Repeating Characters",
    difficulty: "Medium",
    topics: ["Strings", "Sliding Window", "HashMap"],
    lists: ["Blind75", "Neetcode150", "StriverA2Z"],
    link: "https://leetcode.com/problems/longest-substring-without-repeating-characters/",
    platform: "LeetCode",
  },
  {
    id: 14,
    title: "Longest Repeating Character Replacement",
    difficulty: "Medium",
    topics: ["Strings", "Sliding Window"],
    lists: ["Blind75", "Neetcode150"],
    link: "https://leetcode.com/problems/longest-repeating-character-replacement/",
    platform: "LeetCode",
  },
  {
    id: 15,
    title: "Minimum Window Substring",
    difficulty: "Hard",
    topics: ["Strings", "Sliding Window", "HashMap"],
    lists: ["Blind75", "Neetcode150"],
    link: "https://leetcode.com/problems/minimum-window-substring/",
    platform: "LeetCode",
  },
  {
    id: 16,
    title: "Valid Parentheses",
    difficulty: "Easy",
    topics: ["Strings", "Stack"],
    lists: ["Blind75", "Neetcode150", "StriverA2Z"],
    link: "https://leetcode.com/problems/valid-parentheses/",
    platform: "LeetCode",
  },
  {
    id: 17,
    title: "Evaluate Reverse Polish Notation",
    difficulty: "Medium",
    topics: ["Arrays", "Math", "Stack"],
    lists: ["Neetcode150"],
    link: "https://leetcode.com/problems/evaluate-reverse-polish-notation/",
    platform: "LeetCode",
  },
  {
    id: 18,
    title: "Binary Search",
    difficulty: "Easy",
    topics: ["Arrays", "Binary Search"],
    lists: ["Neetcode150", "StriverA2Z"],
    link: "https://leetcode.com/problems/binary-search/",
    platform: "LeetCode",
  },
  {
    id: 19,
    title: "Search a 2D Matrix",
    difficulty: "Medium",
    topics: ["Arrays", "Binary Search", "Matrix"],
    lists: ["Neetcode150", "StriverA2Z"],
    link: "https://leetcode.com/problems/search-a-2d-matrix/",
    platform: "LeetCode",
  },
  {
    id: 20,
    title: "Find Minimum in Rotated Sorted Array",
    difficulty: "Medium",
    topics: ["Arrays", "Binary Search"],
    lists: ["Blind75", "Neetcode150", "StriverA2Z"],
    link: "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/",
    platform: "LeetCode",
  },
  {
    id: 21,
    title: "Search in Rotated Sorted Array",
    difficulty: "Medium",
    topics: ["Arrays", "Binary Search"],
    lists: ["Blind75", "Neetcode150", "StriverA2Z"],
    link: "https://leetcode.com/problems/search-in-rotated-sorted-array/",
    platform: "LeetCode",
  },

  {
    id: 22,
    title: "Reverse Linked List",
    difficulty: "Easy",
    topics: ["Linked List", "Recursion"],
    lists: ["Blind75", "Neetcode150", "StriverA2Z"],
    link: "https://leetcode.com/problems/reverse-linked-list/",
    platform: "LeetCode",
  },
  {
    id: 23,
    title: "Merge Two Sorted Lists",
    difficulty: "Easy",
    topics: ["Linked List"],
    lists: ["Blind75", "Neetcode150", "StriverA2Z"],
    link: "https://leetcode.com/problems/merge-two-sorted-lists/",
    platform: "LeetCode",
  },
  {
    id: 24,
    title: "Reorder List",
    difficulty: "Medium",
    topics: ["Linked List", "Two Pointers"],
    lists: ["Blind75", "Neetcode150"],
    link: "https://leetcode.com/problems/reorder-list/",
    platform: "LeetCode",
  },
  {
    id: 25,
    title: "Remove Nth Node From End of List",
    difficulty: "Medium",
    topics: ["Linked List", "Two Pointers"],
    lists: ["Blind75", "Neetcode150", "StriverA2Z"],
    link: "https://leetcode.com/problems/remove-nth-node-from-end-of-list/",
    platform: "LeetCode",
  },
  {
    id: 26,
    title: "Linked List Cycle",
    difficulty: "Easy",
    topics: ["Linked List", "Two Pointers"],
    lists: ["Blind75", "Neetcode150", "StriverA2Z"],
    link: "https://leetcode.com/problems/linked-list-cycle/",
    platform: "LeetCode",
  },
  {
    id: 27,
    title: "Merge k Sorted Lists",
    difficulty: "Hard",
    topics: ["Linked List", "Divide and Conquer", "Heap"],
    lists: ["Blind75", "Neetcode150"],
    link: "https://leetcode.com/problems/merge-k-sorted-lists/",
    platform: "LeetCode",
  },

  {
    id: 28,
    title: "Invert Binary Tree",
    difficulty: "Easy",
    topics: ["Trees", "DFS", "BFS"],
    lists: ["Blind75", "Neetcode150"],
    link: "https://leetcode.com/problems/invert-binary-tree/",
    platform: "LeetCode",
  },
  {
    id: 29,
    title: "Maximum Depth of Binary Tree",
    difficulty: "Easy",
    topics: ["Trees", "DFS", "BFS"],
    lists: ["Blind75", "Neetcode150", "StriverA2Z"],
    link: "https://leetcode.com/problems/maximum-depth-of-binary-tree/",
    platform: "LeetCode",
  },
  {
    id: 30,
    title: "Same Tree",
    difficulty: "Easy",
    topics: ["Trees", "DFS"],
    lists: ["Blind75", "Neetcode150", "StriverA2Z"],
    link: "https://leetcode.com/problems/same-tree/",
    platform: "LeetCode",
  },
  {
    id: 31,
    title: "Subtree of Another Tree",
    difficulty: "Easy",
    topics: ["Trees", "DFS"],
    lists: ["Blind75", "Neetcode150"],
    link: "https://leetcode.com/problems/subtree-of-another-tree/",
    platform: "LeetCode",
  },
  {
    id: 32,
    title: "Lowest Common Ancestor of a BST",
    difficulty: "Medium",
    topics: ["Trees", "DFS", "Binary Search Tree"],
    lists: ["Blind75", "Neetcode150", "StriverA2Z"],
    link: "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/",
    platform: "LeetCode",
  },
  {
    id: 33,
    title: "Binary Tree Level Order Traversal",
    difficulty: "Medium",
    topics: ["Trees", "BFS"],
    lists: ["Blind75", "Neetcode150", "StriverA2Z"],
    link: "https://leetcode.com/problems/binary-tree-level-order-traversal/",
    platform: "LeetCode",
  },
  {
    id: 34,
    title: "Validate Binary Search Tree",
    difficulty: "Medium",
    topics: ["Trees", "DFS", "Binary Search Tree"],
    lists: ["Blind75", "Neetcode150", "StriverA2Z"],
    link: "https://leetcode.com/problems/validate-binary-search-tree/",
    platform: "LeetCode",
  },

  {
    id: 35,
    title: "Implement Trie (Prefix Tree)",
    difficulty: "Medium",
    topics: ["Trie", "Design"],
    lists: ["Blind75", "Neetcode150", "StriverA2Z"],
    link: "https://leetcode.com/problems/implement-trie-prefix-tree/",
    platform: "LeetCode",
  },
  {
    id: 36,
    title: "Subsets",
    difficulty: "Medium",
    topics: ["Backtracking", "Arrays"],
    lists: ["Neetcode150", "StriverA2Z"],
    link: "https://leetcode.com/problems/subsets/",
    platform: "LeetCode",
  },
  {
    id: 37,
    title: "Combination Sum",
    difficulty: "Medium",
    topics: ["Backtracking", "Arrays"],
    lists: ["Blind75", "Neetcode150", "StriverA2Z"],
    link: "https://leetcode.com/problems/combination-sum/",
    platform: "LeetCode",
  },

  {
    id: 38,
    title: "Number of Islands",
    difficulty: "Medium",
    topics: ["Graphs", "DFS", "BFS", "Matrix"],
    lists: ["Blind75", "Neetcode150", "StriverA2Z"],
    link: "https://leetcode.com/problems/number-of-islands/",
    platform: "LeetCode",
  },
  {
    id: 39,
    title: "Clone Graph",
    difficulty: "Medium",
    topics: ["Graphs", "DFS", "BFS"],
    lists: ["Blind75", "Neetcode150"],
    link: "https://leetcode.com/problems/clone-graph/",
    platform: "LeetCode",
  },
  {
    id: 40,
    title: "Pacific Atlantic Water Flow",
    difficulty: "Medium",
    topics: ["Graphs", "DFS", "BFS", "Matrix"],
    lists: ["Blind75", "Neetcode150"],
    link: "https://leetcode.com/problems/pacific-atlantic-water-flow/",
    platform: "LeetCode",
  },
  {
    id: 41,
    title: "Course Schedule",
    difficulty: "Medium",
    topics: ["Graphs", "DFS", "BFS", "Topological Sort"],
    lists: ["Blind75", "Neetcode150", "StriverA2Z"],
    link: "https://leetcode.com/problems/course-schedule/",
    platform: "LeetCode",
  },

  {
    id: 42,
    title: "Climbing Stairs",
    difficulty: "Easy",
    topics: ["DP", "Math", "Memoization"],
    lists: ["Blind75", "Neetcode150", "StriverA2Z"],
    link: "https://leetcode.com/problems/climbing-stairs/",
    platform: "LeetCode",
  },
  {
    id: 43,
    title: "House Robber",
    difficulty: "Medium",
    topics: ["DP", "Arrays"],
    lists: ["Blind75", "Neetcode150", "StriverA2Z"],
    link: "https://leetcode.com/problems/house-robber/",
    platform: "LeetCode",
  },
  {
    id: 44,
    title: "Coin Change",
    difficulty: "Medium",
    topics: ["DP", "Arrays"],
    lists: ["Blind75", "Neetcode150", "StriverA2Z"],
    link: "https://leetcode.com/problems/coin-change/",
    platform: "LeetCode",
  },
  {
    id: 45,
    title: "Longest Increasing Subsequence",
    difficulty: "Medium",
    topics: ["DP", "Arrays", "Binary Search"],
    lists: ["Blind75", "Neetcode150", "StriverA2Z"],
    link: "https://leetcode.com/problems/longest-increasing-subsequence/",
    platform: "LeetCode",
  },
  {
    id: 46,
    title: "Word Break",
    difficulty: "Medium",
    topics: ["DP", "Strings", "Trie"],
    lists: ["Blind75", "Neetcode150"],
    link: "https://leetcode.com/problems/word-break/",
    platform: "LeetCode",
  },
  {
    id: 47,
    title: "Unique Paths",
    difficulty: "Medium",
    topics: ["DP", "Matrix", "Math"],
    lists: ["Blind75", "Neetcode150", "StriverA2Z"],
    link: "https://leetcode.com/problems/unique-paths/",
    platform: "LeetCode",
  },

  {
    id: 48,
    title: "Set Matrix Zeroes",
    difficulty: "Medium",
    topics: ["Matrix", "Math"],
    lists: ["Blind75", "Neetcode150", "StriverA2Z"],
    link: "https://leetcode.com/problems/set-matrix-zeroes/",
    platform: "LeetCode",
  },
  {
    id: 49,
    title: "Spiral Matrix",
    difficulty: "Medium",
    topics: ["Matrix", "Math"],
    lists: ["Blind75", "Neetcode150", "StriverA2Z"],
    link: "https://leetcode.com/problems/spiral-matrix/",
    platform: "LeetCode",
  },
  {
    id: 50,
    title: "Rotate Image",
    difficulty: "Medium",
    topics: ["Matrix", "Math"],
    lists: ["Blind75", "Neetcode150", "StriverA2Z"],
    link: "https://leetcode.com/problems/rotate-image/",
    platform: "LeetCode",
  },
];
